### ISSUE TITLE
convert single elementType to elementTypes array in policy scope

### ISSUE THREAD

**Issue by yahonggu** [netuitive-community-packages/netuitive-packages-apache-httpd#4]
For example:
"elementType" : null  -> "elementTypes": []
"elementType": "SERVER" -> "elementTypes": ["SERVER"]

**Comment by Grumblesmith** [comment]
@yahonggu is this backwards compatible, or is there urgency to make this update?

**Comment by TheConnMan** [comment]
It is backwards compatible, no urgency.
